### PR TITLE
Made schema more extendable with simple trick. Issue #63 #64 

### PR DESCRIPTION
**Pull request by kosz85**
I made feature request #64 then read issue #63, and after some thought and seeing code found out that it's ultra easy to achieve. I don't think #64 and #63 need to be implemented, but it's nice to have that possibility without modifying base schema code.
Doc class from #63 is implemented as a test `test_validate_kwargs_doc_example`, to show how easy it is.

### CODE REVIEW

**Comment by skorokithakis** [comment]
This looks good to me, it's backwards compatible and doesn't hurt anything. What do you think, @keleshev ?

**Comment by keleshev** [comment]
When would you use something like this? I could see how that works, but I don't understand the use-case.

**Comment by skorokithakis** [comment]
It's for passing data into your subclasses. It's generally good design for `validate()` to pass down extra data, as validation on subclasses may want to use it.

**Comment by kosz85** [comment]
You can easily extend schema, and made it even more powerful, import example from my project:
```
class Import(object):
    """
    >>> Import(Use(lambda x: 'V'), Use(lambda x: 'I')).validate(1)
    'V'
    >>> Import(Use(lambda x: 'V'), Use(lambda x: 'I')).validate(1, importing=True)
    'I'
    """
    def __init__(self, validation, processing):
        self.validation = validation
        self.processing = processing

    def validate(self, data, **kwargs):
        if kwargs.get('importing', False):
            return self.processing.validate(data, **kwargs)
        return self.validation.validate(data, **kwargs)
```
then you define:
```
schema = {
"some_field": And(
        Or(int, LazyType(lazy_model)),
        Import(
            Use(get_object_pk),
            Use(get_object_instance(lazy_model))
        ))
}
```
And use:
- to validate: `Schema(data).validate()`
- to import data `Schema(data).validate(importing=True)`

I have in the same style auto documentation. I use it along with Django, so validate do also exporting for me, and `importing` is changing all ids into objects. So kwargs do the magic for me with very nice interfejs :)

**Comment by kosz85** [comment]
I merged it due to conflicts again.

**Comment by kosz85** [comment]
Please review and merge, I resolved conflicts again

**Comment by skorokithakis** [comment]
This seems pretty straightforward and backwards-compatible, any objections from anyone? @keleshev?

**Comment by keleshev** [comment]
I carefully read code and example and still don't understand—what is an end goal? Could you make a user story for this? Maybe write some docs? 

I suggest to consider this feature after releasing the current version.

**Comment by kosz85** [comment]
@keleshev I give you example few posts ago. You can do things like class `Import`, so you can create your own set of extensions to Schema on top of Schema without editing any part of it. That's powerful, you can  control your `validate` methods using `**kwargs` parameters.

There is nothing really hard, check my example (especially doc tests) and see that output changes when you put different kwarg. I'm using exactly smth like this to serialize and unserialize django models for my planned in time  notifications arguments (to not store models) and in the same time having type validations for them! That's just great!
In my case I push real objects and they all are converted to id's when using `schema.validate(data)` and convert them back to objects few months later when using `validate(data, import=True)`.

**Comment by keleshev** [comment]
@kosz85 I have seen bot the `Import` and `Docs` examples, I just couldn't understand their use cases. I now vaguely understand `Import`'s. How about this instead:

```python
# with #65
schema = Import(Use(check_pk), Use(get_instance))
json = schema.validate(json)  # validate only
mole = schema.validate(json, importing=True)  # validate and load

# without #65
schema = lambda importing=False: Use(get_instance if importing else check_pk)
json = schema().validate(json)  # validate only
mole = schema(importing=True).validate(json)  # validate and load
```

**Comment by kosz85** [comment]
Your example is more like using two different schemas, and is not passing kwargs down the objects. You can't do smth like this without declaring two schemas:
```
schema({
    'smth': {
          'other': Import(Use(check_pk), Use(get_instance))
    }
})
```
I build one schema with functions like `schema_for_model('app.Model')`, and it's only one clean definition without lambda and function hacks. I also don't need to know all supported kwargs when defining schemas. So in future extending it with another kwarg is easier.
Check this:
```
def schema_for_model(model):
    if isinstance(model, basestring):
        lazy_model = lambda: get_model(*model.rsplit('.', 1))
    else:
        lazy_model = lambda: model
    return And(
        Or(int, LazyType(lazy_model)),
        Import(
            Use(get_object_pk),
            Use(get_object_instance(lazy_model))
        ))
```
I don't care what kwargs it support, I just need to use it like this:
```
schema = Schema({
     'user': schema_for_model('auth_app.User'),
     'example': schema_for_model('examples.ExampleModel'),
})
```
If I need i can later add smth new in my schema utils, and use it like this:
```
schema.validate(import=True)
schema.validate(docs=True)
schema.validate(json_schema=True)
```
And I really don't need to change any place where I already use it, just few classes that are defining it.

I hope you will merge it, if not then it's ok, I already use at production my fork anyway.

**Comment by keleshev** [comment]
Sorry, not convinced, I think this is a scope creep for **schema**. **Schema** is fundamentally based on the idea of functions and objects composition, unlike for example JSON schema spec. See how many `lambda`s are there in README. Also, personally dislike `**kwargs` unless all invalid keys are reported.

**Comment by kosz85** [comment]
Your project, your choice, but personally I think you are doing a big mistake. As a last resort to convince you try to implement solution for my problem. Add smth that will load complicated schemas (not smth flat that you mimic with simple lambda), with importing objects  in lazy way resolving models, and  then add  some new key argument, for example `json_export`, which will convert all not base types like deatetitme to json acceptable format. In my  solution it takes writing one  class and use it in 3 more places, in your it would be the number of schemas you have.
All bigger projects use  `**kwargs` there is nothing to be afraid.

**Pull request closed without merging**
