### PR TITLE
[Feature] Add type hints and mypy support

### LINKED ISSUE #296: mypy support
Currently when using the library and calling mypy, it crashes because the library doesn´t seem to have stubs set for mypy.
This also carries types problems with the validations; mypy doesn´t follow the types of the validated data

### PR DESCRIPTION
**Pull request by qequ**
Updated package so it's mypy compatible 

Fixes #296

### CODE REVIEW

**Comment by skorokithakis** [comment]
Hello, thanks for this! Did you use Black on the code? If so, could you please add it to CI?

**Comment by qequ** [comment]
@skorokithakis I've added a CI job for check black linting :+1:

**Comment by skorokithakis** [comment]
This looks good, thank you! To speed up the review, is there any way you could make your changes to schema.py and *not* run Black on it? Then I can review only your changes, and I'll run Black and push to your PR, and then merge.

**Comment by qequ** [comment]
@skorokithakis tough I ran Black there are no significant changes made on the code by Black. At most there are three or four methods/functions signatures formatted to multiple lines, but most of the code remains unchanged

**Comment by skorokithakis** [comment]
Oh, all those changes are manual? OK, I will review ASAP, thanks!

**Comment by qequ** [comment]
@skorokithakis any updates on this?

**Comment by skorokithakis** [comment]
Sorry, this looks good to me. Which Python versions can run this? I worry that it uses syntax that's a bit too recent...

**Comment by qequ** [comment]
@skorokithakis I have made some updates and tested it up to  python3.6 and works normally

**Comment by skorokithakis** [comment]
When you say "up to", what do you mean? 2.7 to 3.6?

**Comment by qequ** [comment]
@skorokithakis I've tested from 3.6 to 3.10 and works fine. 3.5 and backwards versions doesn't support types

**Comment by skorokithakis** [comment]
In that case, that's fine, but the setup.py classifiers/etc needs to be changed to the proper supported versions.

**Comment by qequ** [comment]
@skorokithakis updated classifiers

**Review by skorokithakis — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
