### PR TITLE
Fixing failing tests for error formatting feature. (#98)

### PR DESCRIPTION
**Pull request by bernalrs**
Notice that the tests were failing would be good if we could include this feature in the next release.

### CODE REVIEW

**Comment by skorokithakis** [comment]
This is for when the user hasn't specified an error string, correct?

**Comment by bernalrs** [comment]
Yes that right in some scenarios we are expecting None to be included in the error list it appears this was the intended design however I am not sure about the rationale behind the decision.

**Comment by skorokithakis** [comment]
Hmm, yes, I'm not aware either, @keleshev would know. I'm good to merge this, can you split the long lines a bit so all tests pass?

**Comment by bernalrs** [comment]
All good sorry about the lines length my devenv is set to 120 characters.

**Comment by skorokithakis** [comment]
No problem, thank you!

**Comment by bernalrs** [comment]
Could you please shed light into the process getting this into master and schema's next release ?

**Comment by skorokithakis** [comment]
Sure, it's basically "if you care enough to submit a PR, you should get a quick release". Therefore, [your fix is now in](https://pypi.python.org/pypi/schema/0.6.1). Thanks again!

**Pull request merged**
