### PR TITLE
Update schema.py

### PR DESCRIPTION
**Pull request by gusmonod**
This issue #121 is also a problem for me. There is a simple fix to the test error in #123 as well!

Here it is.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Fantastic, thank you!

**Comment by gusmonod** [comment]
can you please update PyPI? Thanks!

**Comment by skorokithakis** [comment]
I'll give people some time to potentially report issues first, to avoid last time's SNAFU :P

**Comment by gusmonod** [comment]
Sure, makes sense!

**Comment by gusmonod** [comment]
Hi @skorokithakis, now that you have updated master to add the copy test as well as this PR, can you please update PyPI? I would prefer to use the latest version instead of the partially correct 0.6.3

**Comment by skorokithakis** [comment]
Done!

**Pull request merged**
