### PR TITLE
Adding serialization test

### PR DESCRIPTION
**Pull request by DaMaillard**
issue #121

### CODE REVIEW

**Comment by skorokithakis** [comment]
Damn, this breaks the tests. Can you fix it?

**Comment by skorokithakis** [comment]
I'm going to have to revert the previous release if this doesn't get fixed within the next half hour, I'm afraid :/

**Comment by gusmonod** [comment]
Here is a simple way to fix it: instead of using an empty list, just use `None` and then let a list be built with `[None]`

**Comment by gusmonod** [comment]
Oh, and @skorokithakis, I think you should also add this to test that there is no regression.

**Comment by skorokithakis** [comment]
I don't understand how this worked (although it may not have). It's missing an import of `copy` and typos `s1` to `s`. I guess it never worked.

**Pull request merged**
