### PR TITLE
Some performance improvements

### PR DESCRIPTION
**Pull request by some-0n3**
Hi,
I like your library, but found it a bit slow. I tried to speed up things, which made the code a little more messy. But in my tests it run roughly twice as fast.
I tested it with 10k examples from a wiktionay dump. The tests were mostly positive (all examples passed), but  contained some `Or` schemas that failed regularly.

I run the tests with python 2.7, 3.6 and  pypy, the pypy tests had a skip, all the others were successful.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thanks for this! It's a large PR, so it might take a bit of time to review.

**Comment by some-0n3** [comment]
Ok, this is (hopefully) my last edit for this.
Sorry that the first commit was abit too messy, had some trouble with tox (my native python is python 3).
Now everything should be covered (except  "is_valid") and somewhat more readable.

**Comment by skorokithakis** [comment]
@rmorshea It's going slowly because it's pretty large and I'm swamped these days :/ Have you reviewed it? If so, I'll trust your assessment (although the conflicts will need to be resolved).

**Comment by rmorshea** [comment]
@skorokithakis I have not reviewed it, however I'll see if I can make time this week.

**Comment by rmorshea** [comment]
@some-0n3 do you think you'd be able to hop on a call to chat about this. Maybe google hangouts? I think that the changes here are good. It's just hard to review this without a solid hour to do so. This is just going to keep getting pushed back and refactoring will become impossible.

If so, what time zone are you in. I'm PST.

**Pull request closed without merging**
