### PR TITLE
Apply ignore flag recursively for dict

### PR DESCRIPTION
**Pull request by hangyan**
#131

### CODE REVIEW

**Comment by skorokithakis** [comment]
This looks good to me, are there any downsides? Does it change any semantics in undesirable ways?

**Comment by hangyan** [comment]
@skorokithakis I think it's natural for people to think this flag is recursively. I have add the support for `list(dict)` too. There may be one downside, for example: `Schema([1, 0]).validate([1, 1, 0, 1])`, it we add the ignore flag, `Schema([1, 0], ignore_extra_keys=True).validate([1, 1, 0, 1, 2])`, it has no effect for simple types. But that's also make sense, because only `dict` have keys. By the we, the CI test always failed at env `pypy3`, is there something wrong on the env? Can anyone fix it? Thanks!

**Comment by skorokithakis** [comment]
That makes sense, thanks. The `pypy3` test is problematic, yes. The example, `Schema([1, 0], ignore_extra_keys=True).validate([1, 1, 0, 1, 2])`, will fail to validate, correct? It *should* fail to validate, as, as you say, only dicts have keys.

**Comment by hangyan** [comment]
Yes, it will fail, it seems no need to add this check to unittest, so i didn't. I can give a screenshot:

image

**Comment by skorokithakis** [comment]
Great, thank you!

**Comment by hangyan** [comment]
Thanks. (I forgot to update the docs.. will do it as soon as possible!

**Pull request merged**
