### PR TITLE
Implement Forbidden.

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
See the documentation and inline comments for more details.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
I'm completely open to renaming the class, but unlike some other additions I've made on top of schema, this one seemed generic enough that it could be upstreamed, good name or not :)

**Comment by skorokithakis** [comment]
Hmm, this is an interesting addition, I think I like it. @keleshev, what do you think?

@MathieuDuponchelle, can you fix the failing tests in the mean time?

**Comment by MathieuDuponchelle** [comment]
Done too :)

**Comment by MathieuDuponchelle** [comment]
@skorokithakis , should I rebase this ?

**Comment by skorokithakis** [comment]
Yes please. Looking at it again, I would like to merge it when tests pass, it seems like a very useful feature (especially the fact that you can forbid based on matching values).

I'm wondering, however, whether another way might be more practical, when forbidding values. The semantics seem a bit wrong, as it seems to me that forbidding a value should be closer to `{"key": Forbidden("value")}`. Unfortunately, that would be problematic in allowing other values and with multiple keys, whereas your current proposal's usage is clear enough. Obviously we can't have something like `{"key": int, "key": Forbidden(string)}`. I'm probably nitpicking, and what you've done is fine.

@keleshev, do you want to chime in?

**Comment by MathieuDuponchelle** [comment]
Rebased then :)

I see your point with "value-based forbidding", but I'm not sure there's another more satisfying solution, this one has the advantage of "combinability" with Optional, I think as long as it is explicitly documented it should be fine.

afaict the failing test on travis isn't due to this PR, but some sort of setup issue ?

**Comment by skorokithakis** [comment]
Yeah, I thought I fixed the tests issue, but clearly not. Good enough for me, although I wanted @keleshev to opine on this. I guess we can merge now, thank you for all your help!

**Pull request merged**
