### PR TITLE
Fix reliance on `__name__` of callables, fixes #56

### LINKED ISSUE #56: doesn't work with operator.methodcaller
from operator import methodcaller
    from schema import Schema

    f = methodcaller('endswith', '.csv')
    assert f('test.csv')

    Schema(f).validate('test.csv')

    AttributeError: 'operator.methodcaller' object has no attribute '__name__'

We can't assume that all callables have a `__name__`, it would seem.

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #56.

### CODE REVIEW

**Comment by sjakobi** [comment]
Anybody know a better name than `callable_str`?

And does that function possibly need `_` as a prefix?

**Comment by skorokithakis** [comment]
I think that the method does need an underscore as a prefix, it's not meant to be exported by the module. Other than that, I'm ready to merge this.

**Comment by skorokithakis** [comment]
Oops, looks like there's a merge conflict. Can you resolve that so I can merge this?

**Comment by sjakobi** [comment]
Fixed the merge conflict! Cheers!

**Comment by skorokithakis** [comment]
Thank you!

**Pull request merged**
