### PR TITLE
Fix Or reset() when Or is Optional

### PR DESCRIPTION
**Pull request by julienduchesne**
This fixes an issue in https://github.com/keleshev/schema/pull/174. When Or was Optional, the reset method was not called

### CODE REVIEW

**Comment by skorokithakis** [comment]
This looks good to me, is it good to merge?

**Comment by julienduchesne** [comment]
Well tests fail but I'm a bit puzzled. Tox runs fine on my machine :tm:

**Comment by skorokithakis** [comment]
Yeah, that's very odd, and it works on 3.6, and I don't see any backwards-incompatible features used. I've restarted the job, we'll see.

**Comment by julienduchesne** [comment]
I managed to make it fail locally. It is very flaky, weirdly. I will investigate and comment again when it is fixed

**Comment by skorokithakis** [comment]
No, it fails, this is extremely odd. Does it work for you under 3.5?

**Comment by skorokithakis** [comment]
Ah, alright, thanks!

**Comment by skorokithakis** [comment]
It was the guaranteed dictionary order, wasn't it.

**Comment by julienduchesne** [comment]
Yes, it only seemed to fail in 3.5. At least on my machine. Now it's pep8 :man_facepalming:

**Comment by skorokithakis** [comment]
Thank you!

**Pull request merged**
