### PR TITLE
Clean up module namespace

### PR DESCRIPTION
**Pull request by sjakobi**
As [requested](https://github.com/keleshev/schema/issues/59#issuecomment-148041390).

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thanks for the PR! Can you resolve the conflicts so I can merge?

**Comment by sjakobi** [comment]
> Thanks for the PR! Can you resolve the conflicts so I can merge?

Done!

**Comment by keleshev** [comment]
@sjakobi nice that you moved `MARKER` to inner scope, maybe we could do same with priorities? Like:

```python
class _Priority:
    COMPARABLE, CALLABLE, VALIDATOR, TYPE, DICT, ITERABLE = range(6)
```

Then, I think, we don't need `__all__` at all. But these details are up to you @sjakobi and @skorokithakis. Just a suggestion.

**Comment by sjakobi** [comment]
Hi @keleshev,

> maybe we could do same with priorities?

Personally I would find it a bit obfuscating if there was a separate class that serves only to prevent some constants from being exported.
To me, `__all__` is the much cleaner solution that clearly says what is visible from the outside and what is not.

More thoughts and opinions? Maybe a user perspective, @jab?

**Comment by skorokithakis** [comment]
@keleshev, I'm okay with `__all__` (even though we don't need it), because it avoids things creeping into the namespace accidentally. Are you good to merge this? Since it's only about the namespace cleanup, we can handle any other features in a later PR, so as to not hold up the release.

**Comment by keleshev** [comment]
Fine with me.

**Pull request merged**
