### PR TITLE
Implement Const validator to keep data unchanged

### PR DESCRIPTION
**Pull request by insideable**
please take a look in `test_schema.py` to see use case example for `Const`.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thank you, I like this and it seems simple enough. Could you get the tests passing? You can remove the Python3.3 interpreter one, as that's not your fault, but I would like the PEP8 tests to be passing.

**Comment by insideable** [comment]
@skorokithakis I have fixed pep8, but py26, py33 and pypy still failed due these versions of python interpreters are missed. Should I change something in `.travis.yml` ?

**Comment by skorokithakis** [comment]
Yes please, they need to be removed from there.

**Comment by insideable** [comment]
@skorokithakis here we go!

**Comment by skorokithakis** [comment]
Thank you!

**Pull request merged**
