### PR TITLE
Add 'Use' to schema.__all__

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
I tend to do `from schema import *`, didn't initially
understand why Use didn't want to come :)

### CODE REVIEW

**Comment by skorokithakis** [comment]
Oops, thanks! Although, you're missing a comma, so you broke the package :)

**Comment by MathieuDuponchelle** [comment]
Oops, thanks! :P 

I modified the import in the test to use that form, that way what's in __all__ will also be tested in the future :)

**Comment by MathieuDuponchelle** [comment]
Fixed :)

**Comment by skorokithakis** [comment]
Thanks!

**Pull request merged**
