### PR TITLE
Feature/json schema descriptions

### PR DESCRIPTION
**Pull request by jcbedard**
Another feature for #180 
 - Added the Literal type for adding a description to JSON schemas
 - Fixed new bugs introduced by the Literal type
 - Added tests to ensure the Literal type was working as expected 

This is a direct continuation to PR #206

### CODE REVIEW

**Comment by skorokithakis** [comment]
Hmm, why so many changes here? Looks like most of it is reformatting?

**Comment by jcbedard** [comment]
unfortunately black didn't like my formatting which was failing travis CI so I ran it through black

**Comment by skorokithakis** [comment]
I'm confused, where did black not like your formatting? We should standardize on black, I think, so the code will look consistent from now on.

**Comment by jcbedard** [comment]
I didn't know you guys used black with line length 120 so it created huge formatting changes, thus I committed it again with line 120 and now as you see everything passed

**Comment by skorokithakis** [comment]
I have created #209 so this won't happen again, hopefully.

**Comment by skorokithakis** [comment]
Is the new `Literal` type only intended to be used in JSONSchema? Or is there another use?

**Comment by jcbedard** [comment]
only to be used in JSONSchema right now, this is most useful when using autocomplete, a description appears next the the key name

**Comment by skorokithakis** [comment]
In that case, looks good to me!

**Pull request merged**
